version: '3.5'
services:
  php:
    container_name: php
    build:
      context: docker/docker
      dockerfile: php.Dockerfile
    environment:
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      PHP_XDEBUG_REMOTE: ${PHP_XDEBUG_REMOTE}
    volumes:
      - "./:/var/www/html"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/logs/nginx:/var/log/nginx/"
      - "./:/var/www/html"

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: 'on-failure'
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
      - "./docker/config/mysql/custom.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/logs/mysql/query.log:/var/log/query.log"
    ports:
      - "3346:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: 'on-failure'
